[package]
name = "obscura"
version = "0.4.0"
edition = "2021"
authors = ["Ethan Aldrich <Add.email.here>"]
description = "A Rust implementation of the Obscura blockchain protocol."
repository = "https://github.com/0x000null/obscura"

[dependencies]
ed25519-dalek = "1.0"
rand = "0.7"
rand_core = "0.5"
sha2 = "0.9"
chacha20 = "0.9"
typenum = "1.16"
log = "0.4"
env_logger = "0.10"
serde_json = "1.0"
hex = "0.4"
bincode = "1.3"
# Dependencies for message serialization
byteorder = "1.4"
thiserror = "1.0"
rayon = "1.8"
num_cpus = "1.16"

[build-dependencies]
cc = "1.0" 
