use std::time::Duration;

#[derive(Clone, Copy, Debug)]
pub struct DandelionTimings {
    pub fluff_propagation_delay_min_ms: u64,
    pub fluff_propagation_delay_max_ms: u64,
    pub stem_path_recalculation_interval: Duration,
    pub entropy_source_refresh_interval: Duration,
    pub decoy_generation_interval_ms: u64,
    pub max_batch_wait_ms: u64,
    pub timing_jitter_range_ms: u64,
    pub pattern_history_window: Duration,
    pub anonymity_set_rotation_interval: Duration,
    pub network_traffic_analysis_window: Duration,
    pub transaction_graph_sampling_window: Duration,
    pub entropy_measurement_interval: Duration,
    pub aggregation_timeout_ms: u64,
    pub stem_batch_timeout_ms: u64,
    pub stem_fluff_transition_min_delay_ms: u64,
    pub stem_fluff_transition_max_delay_ms: u64,
    pub routing_table_refresh_interval_ms: u64,
    pub circuit_max_age: Duration,
}

impl DandelionTimings {
    pub const DEFAULT: Self = Self {
        fluff_propagation_delay_min_ms: 50,
        fluff_propagation_delay_max_ms: 500,
        stem_path_recalculation_interval: Duration::from_secs(600),
        entropy_source_refresh_interval: Duration::from_secs(300),
        decoy_generation_interval_ms: 30000,
        max_batch_wait_ms: 5000,
        timing_jitter_range_ms: 100,
        pattern_history_window: Duration::from_secs(3600),
        anonymity_set_rotation_interval: Duration::from_secs(1800),
        network_traffic_analysis_window: Duration::from_secs(3600),
        transaction_graph_sampling_window: Duration::from_secs(7200),
        entropy_measurement_interval: Duration::from_secs(600),
        aggregation_timeout_ms: 2000,
        stem_batch_timeout_ms: 3000,
        stem_fluff_transition_min_delay_ms: 1000,
        stem_fluff_transition_max_delay_ms: 5000,
        routing_table_refresh_interval_ms: 30000,
        circuit_max_age: Duration::from_secs(3600),
    };
}

#[derive(Clone, Copy, Debug)]
pub struct DandelionPaths {
    pub min_routing_path_length: usize,
    pub max_routing_path_length: usize,
    pub max_multi_hop_length: usize,
    pub min_as_diversity: usize,
    pub min_country_diversity: usize,
    pub min_subnet_diversity_ratio: f64,
    pub route_diversity_cache_size: usize,
    pub route_reuse_penalty: f64,
    pub diversity_score_threshold: f64,
    pub path_pattern_cache_size: usize,
    pub pattern_similarity_threshold: f64,
    pub max_pattern_frequency: f64,
    pub fluff_entry_points_min: usize,
    pub fluff_entry_points_max: usize,
}

impl DandelionPaths {
    pub const DEFAULT: Self = Self {
        min_routing_path_length: 2,
        max_routing_path_length: 10,
        max_multi_hop_length: 3,
        min_as_diversity: 2,
        min_country_diversity: 2,
        min_subnet_diversity_ratio: 0.6,
        route_diversity_cache_size: 1000,
        route_reuse_penalty: 0.3,
        diversity_score_threshold: 0.7,
        path_pattern_cache_size: 100,
        pattern_similarity_threshold: 0.7,
        max_pattern_frequency: 0.1,
        fluff_entry_points_min: 2,
        fluff_entry_points_max: 4,
    };
}

#[derive(Clone, Copy, Debug)]
pub struct DandelionThresholds {
    pub stem_probability: f64,
    pub multi_hop_stem_probability: f64,
    pub use_decoy_transactions: bool,
    pub decoy_transaction_probability: f64,
    pub batch_transactions_before_fluff: bool,
    pub max_batch_size: usize,
    pub adaptive_timing_enabled: bool,
    pub multi_path_routing_probability: f64,
    pub traffic_analysis_protection_enabled: bool,
    pub background_noise_probability: f64,
    pub suspicious_behavior_threshold: u32,
    pub secure_failover_enabled: bool,
    pub privacy_logging_enabled: bool,
    pub encrypted_peer_communication: bool,
    pub dynamic_peer_scoring_enabled: bool,
    pub reputation_score_max: f64,
    pub reputation_score_min: f64,
    pub reputation_decay_factor: f64,
    pub reputation_penalty_suspicious: f64,
    pub reputation_penalty_sybil: f64,
    pub reputation_reward_successful_relay: f64,
    pub reputation_threshold_stem: f64,
    pub reputation_critical_path_threshold: f64,
    pub reputation_weight_factor: f64,
    pub reputation_adaptive_thresholds: bool,
    pub reputation_min_sample_size: usize,
    pub reputation_reliability_bonus: f64,
    pub reputation_enforced_ratio: f64,
    pub anonymity_set_min_size: usize,
    pub min_peers_for_sybil_detection: usize,
    pub anti_snooping_enabled: bool,
    pub max_tx_requests_before_penalty: u32,
    pub dummy_response_probability: f64,
    pub steganographic_hiding_enabled: bool,
    pub differential_privacy_enabled: bool,
    pub laplace_scale_factor: f64,
    pub tor_integration_enabled: bool,
    pub tor_socks_port: u16,
    pub tor_control_port: u16,
    pub mixnet_integration_enabled: bool,
    pub layered_encryption_enabled: bool,
    pub post_quantum_encryption_enabled: bool,
    pub eclipse_defense_ip_diversity_threshold: usize,
    pub eclipse_defense_peer_rotation_percent: f64,
    pub eclipse_attack_threshold: f64,
    pub automatic_attack_response_enabled: bool,
    pub sybil_detection_cluster_threshold: usize,
    pub anonymity_set_max_size: usize,
    pub anonymity_set_dynamic_sizing_enabled: bool,
    pub anonymity_set_k_anonymity_level: usize,
    pub anonymity_set_transaction_correlation_resistance: bool,
    pub plausible_deniability_enabled: bool,
    pub plausible_deniability_dummy_rate: f64,
    pub graph_analysis_countermeasures_enabled: bool,
    pub graph_entropy_threshold: f64,
    pub transaction_flow_randomization_factor: f64,
    pub min_entropy_samples: usize,
    pub transaction_aggregation_enabled: bool,
    pub max_aggregation_size: usize,
    pub stem_batch_size: usize,
    pub routing_table_inference_resistance_enabled: bool,
    pub circuit_rotation_threshold: u32,
}

impl DandelionThresholds {
    pub const DEFAULT: Self = Self {
        stem_probability: 0.9,
        multi_hop_stem_probability: 0.3,
        use_decoy_transactions: true,
        decoy_transaction_probability: 0.05,
        batch_transactions_before_fluff: true,
        max_batch_size: 5,
        adaptive_timing_enabled: true,
        multi_path_routing_probability: 0.15,
        traffic_analysis_protection_enabled: true,
        background_noise_probability: 0.03,
        suspicious_behavior_threshold: 5,
        secure_failover_enabled: true,
        privacy_logging_enabled: false,
        encrypted_peer_communication: true,
        dynamic_peer_scoring_enabled: true,
        reputation_score_max: 100.0,
        reputation_score_min: -100.0,
        reputation_decay_factor: 0.95,
        reputation_penalty_suspicious: -10.0,
        reputation_penalty_sybil: -20.0,
        reputation_reward_successful_relay: 2.0,
        reputation_threshold_stem: 0.5,
        reputation_critical_path_threshold: 50.0,
        reputation_weight_factor: 2.5,
        reputation_adaptive_thresholds: true,
        reputation_min_sample_size: 10,
        reputation_reliability_bonus: 10.0,
        reputation_enforced_ratio: 0.7,
        anonymity_set_min_size: 3,
        min_peers_for_sybil_detection: 5,
        anti_snooping_enabled: true,
        max_tx_requests_before_penalty: 5,
        dummy_response_probability: 0.2,
        steganographic_hiding_enabled: true,
        differential_privacy_enabled: true,
        laplace_scale_factor: 10.0,
        tor_integration_enabled: false,
        tor_socks_port: 9050,
        tor_control_port: 9051,
        mixnet_integration_enabled: false,
        layered_encryption_enabled: true,
        post_quantum_encryption_enabled: false,
        eclipse_defense_ip_diversity_threshold: 3,
        eclipse_defense_peer_rotation_percent: 0.2,
        eclipse_attack_threshold: 0.6,
        automatic_attack_response_enabled: true,
        sybil_detection_cluster_threshold: 3,
        anonymity_set_max_size: 20,
        anonymity_set_dynamic_sizing_enabled: true,
        anonymity_set_k_anonymity_level: 2,
        anonymity_set_transaction_correlation_resistance: true,
        plausible_deniability_enabled: true,
        plausible_deniability_dummy_rate: 0.15,
        graph_analysis_countermeasures_enabled: true,
        graph_entropy_threshold: 0.7,
        transaction_flow_randomization_factor: 0.3,
        min_entropy_samples: 5,
        transaction_aggregation_enabled: true,
        max_aggregation_size: 10,
        stem_batch_size: 5,
        routing_table_inference_resistance_enabled: true,
        circuit_rotation_threshold: 100,
    };
}
