[book]
title = "Obscura Documentation"
authors = ["Obscura Team"]
description = "Documentation for the Obscura project"
src = "."
language = "en"

[output.html]
git-repository-url = "https://github.com/0x000NULL/obscura"
edit-url-template = "https://github.com/0x000NULL/obscura/edit/main/docs/{path}"
site-url = "/" 